---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /create
  failurePolicy: Fail
  name: mcronjob.kb.io.creator
  rules:
  - apiGroups:
    - batch.tutorial.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - cronjobs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /update
  failurePolicy: Fail
  name: mcronjob.kb.io.updator
  rules:
  - apiGroups:
    - batch.tutorial.kubebuilder.io
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - cronjobs
  sideEffects: None
